codr/class_basics/urls.py
from django.urls import path

from . import views

app_name = 'class_basics'

urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    path('success/', views.SucessView.as_view(), name='success'),
    path('animal/create_animal', views.CreateAnimalFormView.as_view(), name='create_animal'),
    path('animal/', views.AnimalListView.as_view(), name='animal'),
    path('animal/dog', views.DogView.as_view(), name='dog'),
    path('animal/cat', views.CatView.as_view(), name='cat'),
    # ex: /polls/5/

    path('publishers/', views.PublisherListView.as_view(), name="publisher"),
    path('publisher/<int:pk>', views.PublisherView.as_view(), name="detail_publisher"),

]


'''
    path('<int:pk>/', views.DetailView.as_view(), name='detail'), #los detailView deben tener en el path la pk
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    '''

codr/codr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('class_basics.urls')),
    path('polls', include('polls.urls')),
    #path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

codr/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'), #los detailView deben tener en el path la pk
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

codr/class_basics/models.py
from django.db import models

# Create your models here.

class Animal(models.Model):
    name = models.CharField("Nombre", max_length=50)
    species = models.CharField("Especie", max_length=50)
    sound = models.CharField("Sonido", max_length=50)

    def __str__(self):
        return f"{self.species}: {self.name}"
    
####################### MODELOS DE LIBROS ~~~~~~~~~~~

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name

class Author(models.Model):
    salutation = models.CharField(max_length=10)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    headshot = models.ImageField(upload_to='author_headshots')

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField()

codr/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now() 
        return now >= self.pub_date >= now - datetime.timedelta(days=1)
        #return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

codr/class_basics/forms.py
from django import forms
from .models import Animal

class CreateAnimalForm(forms.ModelForm):
    class Meta:
        model = Animal
        fields = ['name', 'species', 'sound']

    def __init__(self, *args, **kwargs):
        super(CreateAnimalForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control my-2'

codr/class_basics/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View, generic
from django.contrib import messages

from .forms import CreateAnimalForm
from .models import Animal, Publisher

# Create your views here.

class SucessView(generic.TemplateView):
    template_name = 'class_basics/success.html'

    def get(self, request):
        storage = messages.get_messages(request)
        messageList = [message.message for message in storage]
        return render(request, self.template_name, { 'messages':  messageList})

class IndexView(generic.TemplateView):
    template_name = 'class_basics/index.html'

class AnimalListView(generic.ListView):
    model = Animal
    template_name = 'class_basics/animal.html'
    context_object_name = "animals"

    def get_queryset(self):
        return Animal.objects.all().values()

class AnimalView(View):
    animal = 'animal'
    sound = "Sound of animal"

    def get(self, request):
        return HttpResponse(f"{self.animal}: {self.sound}")

class CatView(AnimalView):
    animal = 'cat'
    sound = 'miau'

class DogView(AnimalView):
    animal = 'dog'
    sound = 'guau'

class CreateAnimalFormView(View):
    form_class = CreateAnimalForm
    initial = {'name': 'Bobby'}
    template_name = 'class_basics/create_animal.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            name = form['name'].value()
            species = form['species'].value()
            form.save()
            messages.success(request, f'{name} the {species} was created.')
            return redirect('class_basics:success')

        return render(request, self.template_name, {'form': form})
    
########################

class PublisherListView(generic.ListView):
    model = Publisher
    template_name = 'publishers/publishers.html'

    def get_queryset(self):
        return Publisher.objects.all()
    
class PublisherView(generic.DetailView):
    model = Publisher
    template_name = "publishers/publisher.html"
    context_object_name = "publisher"

codr/django_tutorial/views.py
from django.shortcuts import render

# Create your views here.

codr/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

codr/class_basics/templates/class_basics/animal.html
{% extends "master.html" %}

{% block content %}

{% if animals %}
<ul>
    {% for animal in animals %}
        <li> {{animal.name}} - {{animal.species}} - {{animal.sound}}</li>
    
    {% endfor %}

</ul>
{% else %}
<p> No animals.</p>
{% endif %}

{% endblock %}

codr/class_basics/templates/class_basics/create_animal.html
{% extends "master.html" %}

{% block content %}
    <div class="col-6 mx-auto">
        {% comment "Por ahora no usamos esta sección" %}
        {% if msg %}
            <div class="alert alert-success" role="alert">
                {{ msg }}
            </div>
            <div>
                <ul><li>
                    <a href="/">Volver a Inicio</a>
                </li></ul>
            </div>
        {% endif %}
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        {% endcomment %}

        {% if form %}
        <h1 class="mt-3 mb-5">Crear Animal</h1>
        <form action="{% url 'class_basics:create_animal' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary px-2 mt-3" value="Crear Animal">
        </form>
        {% endif %}
    </div>
{% endblock %}

codr/class_basics/templates/class_basics/index.html
{% extends "master.html" %}

{% block content %}
{% endblock %}

codr/class_basics/templates/class_basics/success.html
{% extends 'master.html' %}

{% block content %}

{% for msg in messages %}
    {{msg}}
{% endfor %}
{% endblock %}

codr/class_basics/templates/master.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Index{% endblock %}</title>
  <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <!-- Bootrstap Hoja de Estilos -->
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <!-- Bootstrap Icons -->
  <link rel="stylesheet" href="{% static 'bootstrap-icons.css' %}">
  <!-- Hoja principal de estilos -->
  <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body>

<div class="container">
  <div class="topnav mb-3">
    <a href="{% url 'class_basics:index' %}">HOME</a> |
    <a href="{% url 'class_basics:animal' %}">ANIMAL</a> |
    <a href="{% url 'class_basics:create_animal' %}">CREATE</a> |
    <a href="{% url 'class_basics:dog' %}">PERRO</a> |
    <a href="{% url 'class_basics:cat' %}">GATO</a>
  </div>
  {% block content %}
  {% endblock %}
</div>

</body>
</html>

codr/class_basics/templates/publishers/publisher.html
{% extends 'master.html' %}

{% block content %}
    Publisher.{{publisher.id}}

    <ul>
        <li>{{publisher.name}}</li>

        <li>{{publisher.address}}</li>
    </ul>

{% endblock %}

codr/class_basics/templates/publishers/publishers.html
{% extends "master.html" %}

{% block content %}
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href="{% url 'class_basics:bdetail_publisher' publisher.id %}">{{ publisher.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

codr/polls/templates/polls/detail.html
{% extends 'polls/master.html' %}

{% block content %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
{% endblock %}

codr/polls/templates/polls/index.html
{% extends 'polls/master.html' %}

{% block content %}
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

codr/polls/templates/polls/master.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    </head>
    <body>
        {% block content %}
        {% endblock %}

    </body>
</html>

codr/polls/templates/polls/results.html
{% extends 'polls/master.html' %}

{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}