hello_world/hello_world/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('hello_world_app.urls')),
    path('admin/', admin.site.urls),
]

hello_world/hello_world_app/urls.py
from django.urls import path
from . import views

from .views import (
    main_page,
    hello_world_page,
    all_members_page,
    detail_member_page,
    create_member_page,
    update_member_page,
    delete_member_page,
)

app_name = 'hello_world'

urlpatterns = [
    path('', main_page, name='main'),
    path('hello_world/', hello_world_page, name='hello_world'),
    path('members/', all_members_page, name='all_members'),
    path('members/create/', create_member_page, name='create_member'),
    path('members/update/<slug:slug>', update_member_page, name='update_member'),
    path('members/delete/<slug:slug>', delete_member_page, name='delete_member'),
    path('members/<slug:slug>/', detail_member_page, name='detail_member'),

]

hello_world/hello_world_app/models.py
from django.db import models
from django.urls import reverse

import uuid, datetime


# Create your models here.

def get_time_today():
    return datetime.date.today()

def generate_slug_hash():
    return str(uuid.uuid1())[:8]

class Member(models.Model):
    id = models.IntegerField(primary_key=True)
    firstname = models.CharField(max_length=255) #campo de texto. 
    lastname = models.CharField(max_length=255)
    phone = models.CharField(max_length=20, null=True)
    joined_date = models.DateField(default=get_time_today, null=True)
    slugh_hash = models.CharField(max_length=8,default=generate_slug_hash, null=False)
    slug = models.SlugField(default="", null=False)

    def __str__(self):
        return f"{self.firstname} {self.lastname}"
    
    def get_absolute_url(self):
        return reverse('hello_world:detail_member', args=[self.slug])

hello_world/hello_world_app/forms.py
from .models import Member
from django import forms 

class CreateMemberForm(forms.ModelForm):
    phone = forms.CharField(required=False)
    
    class Meta:
        model = Member
        fields = ('firstname', 'lastname', 'phone',)


class UpdateMemberForm(forms.ModelForm):
    firstname = forms.CharField(required=False)
    lastname = forms.CharField(required=False)
    phone = forms.CharField(required=False)
    
    class Meta:
        model = Member
        fields = ('firstname', 'lastname', 'phone',)

hello_world/hello_world_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

from .models import Member, generate_slug_hash
from .forms import CreateMemberForm, UpdateMemberForm

class MyView(generic.TemplateView):
  pass

class AllMembersView(generic.ListView):
  template_name = 'all_members.html'
  context_object_name = "my_members"

  def get_queryset(self):
    return Member.objects.all().values()

class MemberView(generic.DetailView):
  template_name = 'member.html'
  context_object_name = "my_member"

  def get_object(self):
    self.member = get_object_or_404(Member, slug=self.kwargs['slug'])
    return self.member


def generate_slug(firstname, lastname, slug_hash):
  return f"{firstname}-{lastname}-{slug_hash}".lower().replace(" ", "")

class CreateMemberView(generic.CreateView):
    template_name = "create_member.html"
    form_class = CreateMemberForm
    
    def post(self, request, *args, **kwargs):
      form = self.form_class(request.POST)
      if form.is_valid():
        member = form.save(commit=False) #commit = False porque no lo queremos guardar todavía
        member.slug_hash = generate_slug_hash()
        member.slug = generate_slug(member.firstname, member.lastname, member.slug_hash)
        member.save()
        messages.success(request, f"{member} was created successfully")
      else:
        messages.warning(request, 'Form invalid.')
      return redirect(reverse('hello_world:all_members'))

class UpdateMemberView(generic.UpdateView):
    model = Member
    template_name = "update_member.html"
    form_class = UpdateMemberForm
    context_object_name = 'member'

    def get_queryset(self):
      return Member.objects.filter(slug=self.kwargs['slug'])

    def post(self, request, *args, **kwargs):
      slug = self.kwargs['slug']
      member = get_object_or_404(Member, slug=slug)
      form = self.form_class(request.POST)
      if form.is_valid():
        for field in form.cleaned_data:
          if form.cleaned_data[field]:
            setattr(member, field, form.cleaned_data[field])
            
        slug_hash = slug[slug.rfind("-")+1:]
        member.slug = generate_slug(member.firstname, member.lastname, slug_hash)
        member.save()
        messages.success(request, f"{member} was updated successfully")
      else:
        messages.warning(request, 'Form invalid.')
      return redirect(reverse('hello_world:all_members'))

class MemberDeleteView(SuccessMessageMixin,generic.DeleteView):
  model = Member
  template_name = "delete_member.html"
  success_url = reverse_lazy('hello_world:all_members')
  context_object_name = 'my_member'

  def get(self, request, *args, **kwargs):
    my_object = self.get_object()
    messages.success(request, f"{my_object} was deleted successfully")
    return super().get(request, *args, **kwargs)

main_page = MyView.as_view(template_name = "main.html")
hello_world_page = MyView.as_view(template_name = "hello_world.html")
all_members_page = AllMembersView.as_view()
detail_member_page = MemberView.as_view()
create_member_page = CreateMemberView.as_view()
update_member_page = UpdateMemberView.as_view()
delete_member_page = MemberDeleteView.as_view()

hello_world/hello_world_app/templates/all_members.html
{% extends "base.html" %}

{% block title %}
  Hello World - List of all members
{% endblock %}

{% block content %}

{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
{% endif %}

<div class="mycard">
    <h1>Members</h1>
    {% if my_members %}
    <ul>
      {% for member in my_members %}
        <li onclick="window.location = '/members/{{ member.slug }}'">{{ member.firstname }} {{ member.lastname }}</li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No hay miembros en la bdd.</p>
    {% endif %}
  </div>
  <a href="{% url 'hello_world:create_member' %}"><ul class="col-md-8 col-lg-10 mx-auto"><li class="text-center">Go to Create</li></ul></a>
{% endblock %}

hello_world/hello_world_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  
  <!-- Bootrstap Hoja de Estilos -->
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">

  <!-- Bootstrap Icons -->
  <link rel="stylesheet" href="{% static 'bootstrap-icons.css' %}">
  <link rel="stylesheet" href="{% static 'hello_world_app/main.css' %}">
  <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>
<body>

<div class="row">
  <div class="col-md-4 col-lg-2">
    {% include "sidebar.html" %}
  </div>
  <div class="col-md-8 col-lg-10 p-4">
  
    <div class="topnav mb-2">
      <a class="text-decoration-none" href="{% url 'hello_world:main' %}">HOME</a> |
      <a class="text-decoration-none" href="{% url 'hello_world:all_members' %}">MEMBERS</a> |
      <a class="text-decoration-none" href="{% url 'hello_world:create_member' %}"><i class="bi bi-person-add"></i> CREATE</a>
    </div>
  {% block content %}

  {% endblock %}
  </div>
</div>

</body>
</html>

hello_world/hello_world_app/templates/create_member.html
{% extends "base.html" %}

{% block title %}
  Create Member
{% endblock %}


{% block content %}
<div class="col-8 mx-auto">
    {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
    {% endif %}   
    {% if not msg and not error %}
    <h1>Create Member</h1>
    <form action="{% url 'hello_world:create_member' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Create Member">
    </form>
    {% endif %}
</div>
{% endblock %}

hello_world/hello_world_app/templates/delete_member.html
{% extends "base.html" %}

{% block title %}
  Delete Member
{% endblock %}


{% block content %}
<div class="col-8 mx-auto">
    {% if not msg and not error and my_member %}

    <div class="row text-center mt-4 mb-0">
        <!--<form action="{% url 'hello_world:delete_member' my_member.slug %}" method="post">
            {% csrf_token %}
            <input type="submit" class="py-2 px-3 btn btn-success text-white" value="YES">   
            <input type="submit" class="py-2 px-3 btn btn-danger text-white" formaction="{% url 'hello_world:detail_member' my_member.slug %}" value="NO">
        </form>
    -->

      <form method="post">{% csrf_token %}
        <h2 class="mb-3">Are you sure delete {{my_member}}?</h2>
        <input type="submit" class="py-2 px-3 btn btn-primary text-white" value="Confirm">
     </form>

    </div>
    {% endif %}
</div>
{% endblock %}

hello_world/hello_world_app/templates/failure.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block content %}
<div class="col-8 mx-auto">
    {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
    {% endif %}
    <a href="{% url 'hello_world:all_members' %}"><ul class="col-md-8 col-lg-10 mx-auto"><li class="text-center">Back to members</li></ul></a>
</div>
{% endblock %}

hello_world/hello_world_app/templates/hello_world.html
{% extends 'base.html' %}

{% block title %}
Hello World
{% endblock %}
{% block content %}
    <h1>Hello World!</h1>
    <p>Welcome to my first Django project!</p>


    {% include "hero_banner.html" %}
{% endblock %}

hello_world/hello_world_app/templates/hero_banner.html
{% block banner %}
<section class="hero">
    <div class="container">
        <div class="col-lg-6 hero-text">
            <h1 class="display-4 hero-title">Title</h1>
            <h2 class="lead">Description</h2>
            <a class="btn btn-lg btn-outline-dark text-white hero-button" href="#">Click Here</a>
        </div>
    </div>
</section>


{% endblock %}

hello_world/hello_world_app/templates/main.html
{% extends "base.html" %}

{% block title %}
  Hello World
{% endblock %}


{% block content %}
  <!--
  <h1>Hello World</h1>

  <p>Check out all our <a href="hello_world/">hello world</a></p>

  <h3>Members</h3>
  
  <p>Check out all our <a href="members/">members</a></p>
  -->
{% endblock %}

hello_world/hello_world_app/templates/member.html
{% extends "base.html" %}

{% block title %}
    Details about {{ my_member.firstname }} {{ my_member.lastname }}
{% endblock %}

{% block content %}

    <div class="mycard">
        <h1>{{ my_member.firstname }} {{ my_member.lastname }}</h1>
        
        {% if my_member.phone %}<p>Phone: {{ my_member.phone }}</p>{% endif %}
        {% if my_member.joined_date %}<p>Member since: {{ my_member.joined_date }}</p>{% endif %}
        
        
        <ul class="row">
            <li class="col mx-2 li-orange text-end" onclick="window.location = '/members/update/{{ my_member.slug }}'">
                <a class=""><i class="bi bi-person-gear"></i> Update</a> 
            </li>
            <li class="col mx-2 li-red text-end" onclick="window.location = '/members/delete/{{ my_member.slug }}'">
                <a class="me-1"><i class="bi bi-person-dash"></i> Delete</a>
            </li>
        </ul>
    
    </div>
    <a href="{% url 'hello_world:all_members' %}"><ul class="col-md-8 col-lg-10 mx-auto"><li class="text-center">Back to members</li></ul></a>
   
{% endblock %}

hello_world/hello_world_app/templates/sidebar.html
{% block sidebar %}
<div id="sidebar" class="d-flex flex-column flex-shrink-0 p-3 bg-light">
    <a href="/" class="d-flex align-items-center mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul id="sidebar-nav" class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="{% url 'hello_world:main' %}" class="nav-link active d-flex justify-content-around mx-auto" aria-current="page">
        <i class="bi bi-house"></i>
        <span>Home</span>
        </a>
      </li>
      <li>
        <a href="#" class="nav-link d-flex justify-content-around mx-auto link-dark">
        <i class="bi bi-speedometer2"></i>
        <span>Dashboard</span>
        </a>
      </li>
      <li>
        <a href="#" class="nav-link d-flex justify-content-around mx-auto link-dark">
        <i class="bi bi-calendar-day"></i>
        <span>Orders</span>
        </a>
      </li>
      <li>
        <a href="#" class="nav-link d-flex justify-content-around mx-auto link-dark">
        <i class="bi bi-apple"></i>
        <span>Products</span>
        </a>
      </li>
      <li>
        <a href="#" class="nav-link d-flex justify-content-around mx-auto link-dark">
        <i class="bi bi-person"></i>
        <span>Customers</span>
        </a>
      </li>
    </ul>
    <hr>
    {% comment %}
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu text-small shadow">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
    {% endcomment %}
</div>
{% endblock %}

hello_world/hello_world_app/templates/success.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block content %}
<div class="col-8 mx-auto">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
                {{ message}}
        </div>
        {% endfor %}
    {% endif %}
    <a href="{% url 'hello_world:all_members' %}"><ul class="col-md-8 col-lg-10 mx-auto"><li class="text-center">Back to members</li></ul></a>
</div>
{% endblock %}

hello_world/hello_world_app/templates/update_member.html
{% extends "base.html" %}

{% block title %}
  Update Member
{% endblock %}


{% block content %}
<div class="col-8 mx-auto"> 
    {% if not msg and not error %}
    <h1>Update Member</h1>
    <form action="{% url 'hello_world:update_member' member.slug %}" method="post" novalidate>
        {% csrf_token %}
        <fieldset>
            <label for="lastname">First Name:</label>
            <input class="form-control" type="text" name="firstname" value="{{ member.firstname }}">
            <p><small>{{ member.firstname }}</small></p>
        </fieldset>
        <fieldset>
            <label for="lastname">Last Name:</label>
            <input class="form-control" type="text" name="lastname" value="{{ member.lastname }}">
            <p><small>{{ member.lastname }}</small></p>
        </fieldset>
        <fieldset>
            <label for="phone">Phone:</label>
            <input class="form-control" type="text" name="phone" value="{{ member.phone }}">
            <p><small>{{ member.phone }}</small></p>
        </fieldset>
        <input type="submit" class="btn btn-primary" value="Update Member">
    </form>
    {% endif %}
</div>
{% endblock %}


{% comment %}
{% for field in form %}
{{field}}
{% endfor %}

{% endcomment %}